version: "3.8"

services:
  api:
    image: ghkdwldus0807/lead-me-reprocessor:latest
    container_name: log-rep
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - ./app/models:/code/app/models
      - ./logs:/code/logs

    ports:
      - "8001:8001"

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./logs:/code/logs:ro
      - ./promtail-config.yml:/code/promtail-config.yml
    command: -config.file=/code/promtail-config.yml -config.expand-env=true
    environment:
      LOKI_SERVER_IP: ${LOKI_SERVER_IP}
    depends_on:
      - api