server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://${LOKI_SERVER_IP}:3100/loki/api/v1/push

scrape_configs:
  - job_name: log-reprocessor
    static_configs:
      - targets:
          - localhost
        labels:
          job: log-reprocessor
          __path__: /code/logs/app.log
